# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59f7e6807afe2e148f00903f158027c51dd5a98f167981264de76ae7438a38fe3eeafa58f02f7ace790d55964fdaa8104b647fa045e962e9a4d35daeb50dad98

test:
  secret_key_base: 17754c3ba0fea3d8be75974538099f30b92a1ef0c93dde8caf16d569c7e2f2aa148559b7fe2a7441889960d005dfc99e782d9ac0d445ad418d3bdec9ae495407

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
